### ISSUE TITLE
Auth client error on latest HEAD

### ISSUE THREAD

**Issue by pat-s** [calendso/calendso#262]
### Issue Summary

Running on docker, I see the following on latest HEAD (everything was finde before)

```
TypeError: Cannot read property 'Adapter' of undefined
    at Object.<anonymous> (/opt/app/node_modules/next-auth/dist/adapters/index.js:15:29)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/opt/app/node_modules/next-auth/dist/server/index.js:8:40)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.next-auth (/opt/app/.next/server/pages/api/auth/[...nextauth].js:77:18)
    at __webpack_require__ (/opt/app/.next/server/webpack-runtime.js:33:42)
[next-auth][error][client_fetch_error]
https://next-auth.js.org/errors#client_fetch_error session FetchError: invalid json response body at http://localhost:3000/api/auth/session reason: Unexpected token I in JSON at position 0
```

Note that `GOOGLE_API_CREDENTIALS` did not change and I had a working installation before.

### Technical details

- Judging on 8d6b303

Startup is as follows:

```
      sh -c "npx prisma db push
      && npm i --save-dev prisma
      && npm i @prisma/client
      && yarn dev
      && npx prisma studio"
```

**Comment by emrysal** [comment]
Hi @pat-s Did the server restart during the update? We're seeing some issues with `BASE_URL` and `NEXTAUTH_URL`.

**Comment by pat-s** [comment]
Thanks. I am building the docker file from HEAD. 

No other other variables changed - and `NEXT_AUTH` also stayed the same.

**Comment by emrysal** [comment]
Could you try if you can reproduce the issue with both?

```sh
BASE_URL='https://example.com'
NEXTAUTH_URL='https://example.com'
```

**Comment by pat-s** [comment]
I've tried setting both `BASE_URL` and `NEXTAUTH_URL` to either `https://cal.$DOMAIN.com` or `https://cal.$DOMAIN.com/calendso/api/auth` and different variants of it without success.

Wondering what might have changed recently. I did not log the previous git checkout I used where everything worked.

Now I can't even access my profile page anymore because I get `Internal Server Error`; I might need to check again what is wrong here.
Or wait some days/weeks and try again :)

**Comment by emrysal** [comment]
Internal Server Error will have error logs in your server console - I am running my development branches of main so it is unlikely to be inherently broken, what NodeJS version are you running?

**Comment by pat-s** [comment]
> what NodeJS version are you running?

`node-16`.

I am just scratching my head because everything worked for some weeks now :) No blaming on the team, just trying to get things working again.

Note that I am not into node at all and just plumbing things together.

Here's the `Dockerfile` and `docker-compose.yml` for you in case it helps

```
FROM node:16-alpine3.13
RUN mkdir -p /opt/app
WORKDIR /opt/app

# Change to node user
RUN chown node:node .
USER node

# Install only dependencies
COPY --chown=node:node package.json yarn.lock prisma /opt/app/

# force yarn global cache to live in node_modules or will duplicate files
RUN yarn --global-folder ./node_modules/ --cache-folder ./node_modules/

# Install the rest of the code
COPY --chown=node:node . /opt/app

EXPOSE 3000 5555
CMD ["yarn", "dev"]
```

```
version: "2"
services:
  calendso:
    container_name: calendso
    build:
      context: ./calendso-git
    image: calendso
    restart: "unless-stopped"
    command: >
      sh -c "npx prisma db push
      && npm i --save-dev prisma
      && npm i @prisma/client
      && yarn dev
      && npx prisma studio"
    environment:
      DATABASE_URL: 'postgresql://$CONNECTION'
      GOOGLE_API_CREDENTIALS: '$SECRET'
      # NEXTAUTH_URL: '$VALUE'
      # NEXT_PUBLIC_NEXTAUTH_URL: '$VALUE'
      # BASE_URL: 'VALUE'
    ports:
      - '8100:3000'
      - '8110:5555'
```

Note that all the env vars are not always commented out, just put them this way for the example.
They are set according to the documentation:

- NEXTAUTH_URL: `https://subdomain.$DOMAIN/calendso/api/auth`
- NEXT_PUBLIC_NEXTAUTH_URL: `https://subdomain.$DOMAIN/calendso/api/auth`
- BASE_URL: `https://subdomain.$DOMAIN.com`
